name: Update Semver Tags

on:
  push:
    tags:
      - '*.*.*'

jobs:
  update-semver-tags:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
      
      - name: Setup node
        uses: actions/setup-node@5e21ff4d9bc1a8cf6de233a3057d20ec6b3fb69d #v3.8.1
        with:
          node-version: ${{ env.NODE_VERSION }}
      
      - name: Update Semver
        uses: rickstaa/action-update-semver@77e8cb0f3cd805b38ffe25c07236336e05dcb4da
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          major_version_tag_only: false #   true wenn nur Major-Tags wird aktualisiert oder erstellt
          github-token: ${{ secrets.GITHUB_TOKEN }}

      #- name: Extract major and minor versions
      #  id: version
      #  run: |
      #    TAG=${GITHUB_REF#refs/tags/}
      #    MAJOR=$(echo $TAG | cut -d. -f1)
      #    MINOR=$MAJOR.$(echo $TAG | cut -d. -f2)
      #    echo "::set-output name=major::$MAJOR"
      #    echo "::set-output name=minor::$MINOR"
      #    echo "::set-output name=tag::$TAG"