
name: Versioning

on:
  push:
    branches:
      - dbp-557-implement-semV

jobs:
  version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Get current version
        id: get_version
        run: |
          git fetch --tags
          echo ::set-output name=version::$(git describe --tags --abbrev=0)

      - name: Determine version type
        id: bump_version
        run: |
          version=${{ steps.get_version.outputs.version }}
          major=$(echo "$version" | cut -d '.' -f 1 | sed 's/v//')
          minor=$(echo "$version" | cut -d '.' -f 2)
          patch=$(echo "$version" | cut -d '.' -f 3)

          # Annahme: Anpassung basierend auf Commit-Nachrichten oder anderem Trigger
          # Dies ist ein einfaches Beispiel und muss möglicherweise angepasst werden
          if git log -1 --pretty=%B | grep -q '#major'; then
            new_version="v$((major+1)).0.0"
          elif git log -1 --pretty=%B | grep -q '#minor'; then
            new_version="v$major.$((minor+1)).0"
          else
            new_version="v$major.$minor.$((patch+1))"
          fi
          echo "::set-output name=version::$new_version"

      - name: Create new tag
        if: github.ref == 'refs/heads/dbp-557-implement-semV'
        uses: anothrNick/github-tag-action@a2c70ae13a881faf2b4953baaa9e49731997ab36
        with:
          tag: ${{ steps.bump_version.outputs.version }}
          message: 'New version ${{ steps.bump_version.outputs.version }}'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
