name: 'Check - Tests & Sonarcloud'

on:
  workflow_call:
    inputs:
      node_version:
        type: string
        description: "Version to use for node"
        required: true
      deploy_stage:
        type: string
        description: "Deployment stage (Some tests need this varaible)"
        default: ""
        required: false
      node_heap_size:
        type: number
        description: "Heap Size for node in MB"
        required: false
        default: 4096
      skip_tests:
        type: boolean
        description: "Skip running the tests and just scan with sonarcloud"
        required: false
        default: false
      timeout_minutes:
        type: number
        description: "Timout in minutes"
        required: false
        default: 10
env:
  NODE_VERSION: ${{ inputs.node_version }} # needed for npm test
  NODE_OPTIONS: "--max-old-space-size=${{ inputs.node_heap_size }}"
  DEPLOY_STAGE: ${{ inputs.deploy_stage }}

jobs:
  tests_sonarcloud:
    name: Tests and Sonarcloud
    runs-on: ubuntu-latest
    permissions:
      contents: read
    timeout-minutes: ${{ inputs.timeout_minutes }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11  #v4.1.1
        with:
          fetch-depth: 0

      - name: Docker check
        run: docker --version

      - name: Inject Secrets
        uses: timheuer/base64-to-file@784a1a4a994315802b7d8e2084e116e783d157be #v1.2.4
        with:
          fileName: 'secrets.json'
          fileDir: './config/'
          # These are placeholder secrets without any significance
          encodedString: ewogICAgIkRCIjogewogICAgICAgICJTRUNSRVQiOiAiVmVyeSBoaWRkZW4gc2VjcmV0IgogICAgfSwKICAgICJLRVlDTE9BSyI6IHsKICAgICAgICAiQURNSU5fU0VDUkVUIjogIkNsaWVudCBTZWNyZXQiCiAgICB9Cn0=

      - name: Setup node
        uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 #v4.0.2
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install dependencies
        run: npm ci --prefer-offline --no-audit

      - name: Run tests
        if: ${{ !inputs.skip_tests }}
        run: npm run test:ci

      - name: Save test artifacts
        if: ${{ !inputs.skip_tests }}
        run: |
          mkdir -p coverage
          mv ./coverage artifacts

      - name: Upload test artifacts
        if: ${{ !inputs.skip_tests }}
        uses: actions/upload-artifact@5d5d22a31266ced268874388b861e4b58bb5c2f3  #v4.3.1
        with:
          name: test-artifacts
          path: artifacts/

      - name: SonarCloud upload
        uses: SonarSource/sonarqube-scan-action@1a6d90ebcb0e6a6b1d87e37ba693fe453195ae25 #v5.3.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_SCANNER_OPTS: "-Dsonar.nodejs.executable=/usr/local/bin/node"