name: Check image with trivy
on:
  workflow_call:
    inputs:
      image_ref:
        description: "Image that should be scanned"
        required: true
        type: string
      severity:
        description: 'Severity filter (default "CRITICAL,HIGH")'
        required: false
        default: "CRITICAL,HIGH"
        type: string
      fail_on_vulnerabilites:
        description: "Whether the workflow should fail if vulnerabilities are found"
        required: false
        default: true
        type: boolean
      ignore-unfixed:
        description: "Ignore vulerabilities without fix"
        required: false
        default: true
        type: boolean

jobs:
  trivy_scan:
    name: Trivy Scan
    runs-on: ubuntu-latest
    permissions:
        packages: read
        security-events: write
    steps:
        # GHCR requires the image to be all lowercase, otherwise trivy can't pull the image
      - name: Create lowercase image ref
        id: image_ref_lower
        env:
            image_ref: '${{ inputs.image_ref }}'
        run: echo "output=${image_ref,,}" >> $GITHUB_OUTPUT

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@7b7aa264d83dc58691451798b4d117d53d21edfe #v0.12.0
        with:
          image-ref: ${{ steps.image_ref_lower.outputs.output }}
          format: "sarif"
          output: "trivy-results.sarif"
          severity: ${{ inputs.severity }}
          exit-code: ${{ inputs.fail_on_vulnerabilites && 1 || 0}}
          ignore-unfixed: ${{ inputs.ignore-unfixed }}

      - name: Upload Trivy scan results to GitHub Security tab
        if: ${{ always() }}
        uses: github/codeql-action/upload-sarif@0116bc2df50751f9724a2e35ef1f24d22f90e4e1 #v2.22.3
        with:
            sarif_file: 'trivy-results.sarif'