name: Scan image with ClamAV

on:
  workflow_call:
    inputs:
      image_ref:
        description: "Image that should be scanned"
        required: true
        type: string

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
    - name: Install ClamAV
      run: |
        sudo apt-get update
        sudo apt-get install -y clamav
    - name: Extract image content
      env:
        IMAGE_REF: '${{ inputs.image_ref }}'
      run: |
        docker create --name scan ${IMAGE_REF@L}
        mkdir tmp_scan
        docker cp scan:/ ./tmp_scan
    - name: Wait until signatures are updated
      timeout-minutes: 2
      run: |
        while true; do
          if sudo grep -q "main.cvd updated" /var/log/clamav/freshclam.log && \
             sudo grep -q "daily.cvd updated" /var/log/clamav/freshclam.log && \
             sudo grep -q "bytecode.cvd updated" /var/log/clamav/freshclam.log; then
            echo "Signatures updated."
            exit 0
          else
            echo "Signatures not updated yet..."
          fi
          sleep 1
        done
    - name: Scanning image content
      run: |
        set +e
        clamscan -ir ./tmp_scan
        if [ $? -eq 1 ]; then
          echo "::error:: Virus findings in image! More details are in the workflow logs."
          exit 1
        fi