name: 'Check - Tests & Sonarcloud'

on:
  workflow_call:
    inputs:
      node_version:
        type: string
        description: "Version to use for node. Takes precedence over version_file."
        required: false
      node_version_file:
        type: string
        description: "File containing the node version (e.g. package.json)."
        required: false
      deploy_stage:
        type: string
        description: "Deployment stage (Some tests need this varaible)"
        default: ""
        required: false
      node_heap_size:
        type: number
        description: "Heap Size for node in MB"
        required: false
        default: 4096
      skip_tests:
        type: boolean
        description: "Skip running the tests and just scan with sonarcloud"
        required: false
        default: false
      timeout_minutes:
        type: number
        description: "Timout in minutes"
        required: false
        default: 10
    secrets:
      SONAR_TOKEN:
        required: true
env:
  NODE_VERSION: ${{ inputs.node_version }} # needed for npm test
  NODE_VERSION_FILE: ${{ inputs.node_version_file }}
  NODE_OPTIONS: "--max-old-space-size=${{ inputs.node_heap_size }}"
  DEPLOY_STAGE: ${{ inputs.deploy_stage }}

jobs:
  validate_inputs:
    runs-on: ubuntu-latest
    steps:
      - name: Validate inputs
        shell: bash
        run: |
          node_version="${{ inputs.node_version }}"
          node_version_file="${{ inputs.node_version_file }}"

          if [[ -z "$node_version" && -z "$node_version_file" ]]; then
            echo "::error::You must provide at least one of: node_version or node_version_file"
            exit 1
          fi

  tests_sonarcloud:
    name: Tests and Sonarcloud
    runs-on: ubuntu-latest
    permissions:
      contents: read
    timeout-minutes: ${{ inputs.timeout_minutes }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0

      - name: Docker check
        run: docker --version

      - name: Inject Secrets
        uses: timheuer/base64-to-file@784a1a4a994315802b7d8e2084e116e783d157be #v1.2.4
        with:
          fileName: 'secrets.json'
          fileDir: './config/'
          # These are placeholder secrets without any significance
          encodedString: ewogICAgIkRCIjogewogICAgICAgICJTRUNSRVQiOiAiVmVyeSBoaWRkZW4gc2VjcmV0IgogICAgfSwKICAgICJLRVlDTE9BSyI6IHsKICAgICAgICAiQURNSU5fU0VDUkVUIjogIkNsaWVudCBTZWNyZXQiCiAgICB9Cn0=

      - name: Setup node
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e #v6.4.0
        with:
          node-version: ${{ env.NODE_VERSION }}
          node-version-file: ${{ env.NODE_VERSION_FILE }}

      - name: Install dependencies
        run: npm ci --prefer-offline --no-audit

      - name: Run tests
        if: ${{ !inputs.skip_tests }}
        run: npm run test:ci

      - name: Save test artifacts
        if: ${{ !inputs.skip_tests }}
        run: |
          mkdir -p coverage
          mv ./coverage artifacts

      - name: Upload test artifacts
        if: ${{ !inputs.skip_tests }}
        uses: actions/upload-artifact@5d5d22a31266ced268874388b861e4b58bb5c2f3  #v4.3.1
        with:
          name: test-artifacts
          path: artifacts/

      - name: SonarCloud upload
        uses: SonarSource/sonarqube-scan-action@1a6d90ebcb0e6a6b1d87e37ba693fe453195ae25 #v5.3.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_SCANNER_OPTS: "-Dsonar.nodejs.executable=/usr/local/bin/node"
