name: 'Check - Nest Lint'

on:
  workflow_call:
    inputs:
      node_version:
        type: string
        description: "Version to use for node"
        required: true

env:
  NODE_VERSION: ${{ inputs.node_version }}

jobs:
  nest_lint:
    name: Nest Lint
    runs-on: ubuntu-latest
    permissions:
      contents: read
    timeout-minutes: 5
    steps:
      - name: Checkout repository
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11  #v4.1.1

      - name: Setup node
        uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 #v4.0.2
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install dependencies
        run: npm ci --prefer-offline --no-audit

      - name: Download all workflow run artifacts
        uses: actions/download-artifact@c850b930e6ba138125429b7e5c93fc707a7f8427 # v4.1.4
        if: ${{ github.repository == 'schulportal-client' }}
        with:
          name: generated
          path: src/api-client/generated

      - name: Run linter
        run: npm run lint