name: Check image and filesystem with trivy
on:
  workflow_call:
    inputs:
      image_ref:
        description: "Image that should be scanned"
        required: false
        default: ""
        type: string
      severity:
        description: 'Severity filter (default "CRITICAL,HIGH")'
        required: false
        default: "CRITICAL,HIGH"
        type: string
      fail_on_vulnerabilites:
        description: "Whether the workflow should fail if vulnerabilities are found"
        required: false
        default: true
        type: boolean
      ignore-unfixed:
        description: "Ignore vulerabilities without fix"
        required: false
        default: true
        type: boolean
      report_location:
        description: "If defined it overrides the reported location (normally <organization>/<image>) of the trivy findings to a specific file (e.g. Dockerfile)"
        required: false
        default: ""
        type: string
      trivyignores:
        description: "comma-separated list of relative paths in repository to one or more .trivyignore files"
        required: false
        default: ""
        type: string
      limit-severities-for-sarif:
        description: "limit severities for SARIF format"
        required: false
        default: false
        type: boolean
      scan_type:
        description: "Choice of scan type: 'image' or 'fs' (filesystem)."
        required: false
        default: 'image'
        type: string
      skip_dirs:
        description: 'comma separated list of directories where traversal is skipped'
        required: false
        default: ''
        type: string
      skip_files:
        description: 'comma separated list of files to be skipped'
        required: false
        default: ''
        type: string

jobs:
  trivy_scan:
    name: Trivy Scan
    runs-on: ubuntu-latest
    permissions:
        packages: read
        security-events: write
    steps:
        # GHCR requires the image to be all lowercase, otherwise trivy can't pull the image
      - name: Create lowercase image ref
        id: image_ref_lower
        env:
            image_ref: '${{ inputs.image_ref }}'
        run: echo "output=${image_ref,,}" >> $GITHUB_OUTPUT
      
      - name: Checkout code
        if: ${{ inputs.trivyignores != '' || inputs.scan_type == 'fs' }}
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Run Trivy vulnerability scanner on image or filesystem
        uses: aquasecurity/trivy-action@ed142fd0673e97e23eac54620cfb913e5ce36c25 # v0.36.0
        with:
          scan-type: ${{ inputs.scan_type }}
          image-ref: ${{ steps.image_ref_lower.outputs.output }} # if scan is for image, will be ignored for filesystem scan
          scan-ref: "." # if scan is for filesystem, will be ignored for image scan
          format: "sarif"
          output: "trivy-results.sarif"
          severity: ${{ inputs.severity }}
          exit-code: ${{ inputs.fail_on_vulnerabilites && 1 || 0}}
          ignore-unfixed: ${{ inputs.ignore-unfixed }}
          limit-severities-for-sarif: ${{ inputs.limit-severities-for-sarif }}
          trivyignores: ${{ inputs.trivyignores }}
          skip-dirs: ${{ inputs.skip_dirs }}
          skip-files: ${{ inputs.skip_files }}
          version: "0.74.0"
        env:
          TRIVY_JAVA_DB_REPOSITORY: public.ecr.aws/aquasecurity/trivy-java-db
          TRIVY_DB_REPOSITORY: public.ecr.aws/aquasecurity/trivy-db

      - name: Override location of findings
        if: ${{ always() && inputs.report_location != '' }}
        run: |
          jq '.runs[].results[].locations[].physicalLocation.artifactLocation.uri |= "${{ inputs.report_location }}"' trivy-results.sarif > trivy-results-tmp.sarif
          mv trivy-results-tmp.sarif trivy-results.sarif
          
      - name: Upload Trivy scan results to GitHub Security tab
        if: ${{ always() }}
        uses: github/codeql-action/upload-sarif@cdf488f595d80d6e07e03d4674febd5ab45fa938 # v4.37.9
        with:
            sarif_file: 'trivy-results.sarif'
            category: 'trivy-${{ inputs.scan_type }}-scan'
