name: 'Check - Nest Lint'

on:
  workflow_call:

env:
  NODE_VERSION: '18'
  DEPLOY_STAGE: 'dev'

jobs:
  nest_lint:
    name: Nest Lint
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout repository
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 #v3.6.0
      - name: Setup node
        uses: actions/setup-node@5e21ff4d9bc1a8cf6de233a3057d20ec6b3fb69d #v3.8.1
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Install dependencies
        run: npm ci --prefer-offline --no-audit
      - name: Run linter
        run: npm run lint