name: 'Check - Nest Test & Sonarcloud'

on:
  workflow_call:
    inputs:
      node_version:
        type: string
        description: "Version to use for node"
        required: true
      deploy_stage:
        type: string
        description: "Deployment stage"
        required: true
      node_heap_size:
        type: number
        description: "Heap Size for node in MB"
        required: false
        default: 4096
      timeout_minutes:
        type: number
        description: "Heap Size for node in MB"
        required: false
        default: 4096
env:
  NODE_VERSION: ${{ inputs.node_version }} # needed for npm test
  NODE_OPTIONS: "--max-old-space-size=${{ inputs.node_heap_size }}"
  DEPLOY_STAGE: ${{ inputs.deploy_stage }}

jobs:
  nest_test_cov:
    name: Nest Test
    runs-on: ubuntu-latest
    permissions:
      contents: read
    timeout-minutes: 10
    steps:
      - name: Checkout repository
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 #v3.6.0

      - name: Docker check
        run: docker --version

      - name: Inject Secrets
        uses: timheuer/base64-to-file@ca9e30baf83f7f26708fb0059af9a0973fe5f27e #v1.2.3
        with:
          fileName: 'secrets.json'
          fileDir: './config/'
          # These are placeholder secrets without any significance
          encodedString: ewogICAgIkRCIjogewogICAgICAgICJTRUNSRVQiOiAiVmVyeSBoaWRkZW4gc2VjcmV0IgogICAgfSwKICAgICJLRVlDTE9BSyI6IHsKICAgICAgICAiQURNSU5fU0VDUkVUIjogIkNsaWVudCBTZWNyZXQiCiAgICB9Cn0=

      - name: Setup node
        uses: actions/setup-node@5e21ff4d9bc1a8cf6de233a3057d20ec6b3fb69d #v3.8.1
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install dependencies
        run: npm ci --prefer-offline --no-audit

      - name: Run tests
        run: npm run test:ci

      - name: Save test artifacts (ensure compatibility to previous implementation)
        run: |
          mkdir -p coverage
          mv ./coverage artifacts

      - name: SonarCloud upload
        uses: SonarSource/sonarcloud-github-action@c25d2e7e3def96d0d1781000d3c429da22cd6252 #v2.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
